In [1]:
squares = [n**2 for n in range(1,99,1)]
print(squares)
evenSquares = [n**2 for n in range(1,99,1) if n % 2 == 0]
print(evenSquares)

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100, 121, 144, 169, 196, 225, 256, 289, 324, 361, 400, 441, 484, 529, 576, 625, 676, 729, 784, 841, 900, 961, 1024, 1089, 1156, 1225, 1296, 1369, 1444, 1521, 1600, 1681, 1764, 1849, 1936, 2025, 2116, 2209, 2304, 2401, 2500, 2601, 2704, 2809, 2916, 3025, 3136, 3249, 3364, 3481, 3600, 3721, 3844, 3969, 4096, 4225, 4356, 4489, 4624, 4761, 4900, 5041, 5184, 5329, 5476, 5625, 5776, 5929, 6084, 6241, 6400, 6561, 6724, 6889, 7056, 7225, 7396, 7569, 7744, 7921, 8100, 8281, 8464, 8649, 8836, 9025, 9216, 9409, 9604]
[4, 16, 36, 64, 100, 144, 196, 256, 324, 400, 484, 576, 676, 784, 900, 1024, 1156, 1296, 1444, 1600, 1764, 1936, 2116, 2304, 2500, 2704, 2916, 3136, 3364, 3600, 3844, 4096, 4356, 4624, 4900, 5184, 5476, 5776, 6084, 6400, 6724, 7056, 7396, 7744, 8100, 8464, 8836, 9216, 9604]


In [2]:
def wordGenerator (word, lines):
    times = 0
    num = 1
    while times < lines:
        out = "Meow "*num
        yield out
        num = num*2
        times += 1
        
Meow = wordGenerator("Meow", 5)
for i in range(5):
    print(next(Meow))



Meow 
Meow Meow 
Meow Meow Meow Meow 
Meow Meow Meow Meow Meow Meow Meow Meow 
Meow Meow Meow Meow Meow Meow Meow Meow Meow Meow Meow Meow Meow Meow Meow Meow 


In [10]:
import numpy as np
np.set_printoptions(suppress=True)

Norm = np.random.default_rng().normal(0, 1, size=(5, 5))
print(Norm)
with np.nditer(Norm, op_flags=['readwrite']) as it:
    for n in it:
        if n > 0.09:
            n[...] = n**2
        else:
            n[...] = 42
print(Norm)
print(Norm[:,3])    

[[ 0.36335988  0.55084432 -0.34347492  0.48565197 -0.75048673]
 [-0.48028737  0.69434474 -0.79061111 -0.49920808 -1.59232729]
 [ 0.00316507 -0.64415587 -1.14008806  0.51227766  1.74095225]
 [-0.39231952  0.32903867 -0.7656731  -2.69573235 -0.4102986 ]
 [ 0.71641384  0.60813476 -0.62373076 -0.51409012 -0.72206826]]
[[ 0.1320304   0.30342947 42.          0.23585784 42.        ]
 [42.          0.48211462 42.         42.         42.        ]
 [42.         42.         42.          0.2624284   3.03091474]
 [42.          0.10826644 42.         42.         42.        ]
 [ 0.5132488   0.36982788 42.         42.         42.        ]]
[ 0.23585784 42.          0.2624284  42.         42.        ]
